import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const coreFeatures = ["pos", "inventory", "customers", "reports"];
const businessFeatures = [
  ...coreFeatures,
  "suppliers",
  "purchases",
  "expenses",
  "customer_credit",
  "reports_profit",
  "exports",
  "appointments",
  "commissions",
  "offline_pos",
];
const allFeatures = [...businessFeatures, "multi_branch"];
const planDefinitions = [
  {
    code: "STARTER",
    name: "Starter",
    monthly: 9900,
    annual: 99000,
    limits: [1, 2, 1, 1000],
    features: coreFeatures,
    public: true,
    order: 10,
  },
  {
    code: "BUSINESS",
    name: "Business",
    monthly: 19900,
    annual: 199000,
    limits: [1, 6, 2, 10000],
    features: businessFeatures,
    public: true,
    order: 20,
  },
  {
    code: "GROWTH",
    name: "Growth",
    monthly: 34900,
    annual: 349000,
    limits: [3, 15, 5, null],
    features: allFeatures,
    public: true,
    order: 30,
  },
  {
    code: "ENTERPRISE",
    name: "Enterprise",
    monthly: 0,
    annual: 0,
    limits: [null, null, null, null],
    features: allFeatures,
    public: true,
    order: 40,
  },
  {
    code: "LEGACY",
    name: "Legacy",
    monthly: 0,
    annual: 0,
    limits: [null, null, null, null],
    features: allFeatures,
    public: false,
    order: 1000,
  },
];

const permissions = [
  ["organization.read", "View organization details"],
  ["organization.update", "Update organization details"],
  ["branch.read", "View branches"],
  ["branch.create", "Create branches"],
  ["branch.update", "Update branches"],
  ["user.read", "View organization users"],
  ["user.invite", "Invite organization users"],
  ["user.update", "Update organization memberships"],
  ["user.remove", "Deactivate organization memberships"],
  ["role.read", "View roles and permissions"],
  ["role.create", "Create organization roles"],
  ["role.update", "Update organization roles"],
  ["role.assign", "Assign roles to organization users"],
  ["audit.read", "View organization audit logs"],
  ["settings.read", "View organization settings"],
  ["settings.update", "Update organization settings"],
  ["billing.read", "View organization subscription and billing"],
  ["billing.manage", "Select, cancel, or resume organization plans"],
  ["platform.subscription.read", "View platform subscriptions"],
  ["platform.subscription.manage", "Manage platform subscriptions"],
  ["platform.billing.read", "View platform billing records"],
  ["platform.billing.manage", "Confirm platform billing payments"],
  ["platform.plan.read", "View platform plan configuration"],
  ["platform.plan.manage", "Manage platform plan configuration"],
  ["catalogue.read", "View catalogue resources"],
  ["category.create", "Create categories"],
  ["category.update", "Update categories"],
  ["brand.create", "Create brands"],
  ["brand.update", "Update brands"],
  ["unit.create", "Create units"],
  ["unit.update", "Update units"],
  ["product.create", "Create products and variants"],
  ["product.update", "Update products and variants"],
  ["inventory.read", "View inventory and stock movement history"],
  ["inventory.opening", "Post opening stock"],
  ["inventory.adjust", "Post stock adjustments"],
  ["inventory.transfer", "Create and send stock transfers"],
  ["inventory.transfer.receive", "Receive stock transfers"],
  ["sale.read", "View sales and recorded payments"],
  ["sale.create", "Complete point-of-sale checkout"],
  ["sale.hold", "Hold sales for later completion"],
  ["sale.cancel_draft", "Cancel draft or held sales"],
  ["sale.refund", "Refund, return, or exchange completed sales"],
  ["shift.open", "Open a cashier register shift"],
  ["shift.read", "View register shifts"],
  ["shift.close", "Close a cashier register shift"],
  ["shift.approve", "Approve register cash variances"],
  ["shift.cash_movement", "Record cash in and cash out movements"],
  ["alert.read", "View operational alerts"],
  ["alert.manage", "Acknowledge and resolve operational alerts"],
  ["catalogue.import", "Import products from CSV"],
  ["catalogue.export", "Export products to CSV"],
  ["sale.discount", "Apply configured sale discounts"],
  ["payment.record", "Record sale payments"],
  ["receipt.print", "View and print sale receipts"],
  ["product.cost.read", "View product cost and sale cost snapshots"],
  ["supplier.read", "View suppliers"],
  ["supplier.create", "Create suppliers"],
  ["supplier.update", "Update suppliers"],
  ["purchase.read", "View purchases and supplier costs"],
  ["purchase.create", "Create purchases"],
  ["purchase.update_draft", "Update draft purchases"],
  ["purchase.receive", "Receive purchased inventory"],
  ["purchase.cancel_draft", "Cancel draft purchases"],
  ["supplier_payment.read", "View supplier payments"],
  ["supplier_payment.create", "Record supplier payments"],
  ["expense.read", "View expenses"],
  ["expense.create", "Record expenses"],
  ["expense_category.read", "View expense categories"],
  ["expense_category.create", "Create expense categories"],
  ["expense_category.update", "Update expense categories"],
  ["customer.read", "View customers"],
  ["customer.create", "Create customers"],
  ["customer.update", "Update customers"],
  ["customer_balance.read", "View customer balances and credit limits"],
  ["customer_payment.read", "View customer repayments"],
  ["customer_payment.create", "Record customer repayments"],
  ["sale.credit", "Complete customer credit sales"],
  ["staff.read", "View staff profiles and capabilities"],
  ["staff.create", "Create staff profiles"],
  ["staff.update", "Update staff profiles and capabilities"],
  ["staff_availability.read", "View staff availability and time off"],
  ["staff_availability.manage", "Manage staff availability and time off"],
  ["appointment.read", "View appointments"],
  ["appointment.read_all", "View all appointments in scope"],
  ["appointment.create", "Create appointments"],
  ["appointment.update", "Reschedule appointments"],
  ["appointment.confirm", "Confirm appointments"],
  ["appointment.start", "Start appointments"],
  ["appointment.complete", "Complete appointments"],
  ["appointment.cancel", "Cancel appointments"],
  ["appointment.no_show", "Mark appointments as no-show"],
  ["appointment.checkout", "Checkout completed appointments"],
  ["commission_rule.read", "View commission rules"],
  ["commission_rule.create", "Create commission rules"],
  ["commission_rule.update", "Update commission rules"],
  ["commission.read", "View commissions"],
  ["commission.read_all", "View all commissions in scope"],
  ["commission.read_own", "View own commissions"],
  ["report.dashboard", "View the reporting dashboard"],
  ["report.sales", "View sales reports"],
  ["report.sales.cost", "View historical cost in sales reports"],
  ["report.profit", "View gross-profit reports"],
  ["report.payments", "View collected-payment reports"],
  ["report.inventory", "View inventory reports"],
  ["report.inventory.valuation", "View inventory cost valuation"],
  ["report.purchases", "View purchase reports"],
  ["report.suppliers", "View supplier balance reports"],
  ["report.expenses", "View expense reports"],
  ["report.customers", "View customer reports"],
  ["report.customer_balances", "View customer credit balances"],
  ["report.appointments", "View appointment reports"],
  ["report.commissions", "View commission reports"],
  ["report.export", "Export authorized reports"],
  ["reconciliation.submit", "Submit own end-of-day cashier cash-up"],
  [
    "reconciliation.read_all",
    "View branch or organization cash reconciliations",
  ],
  ["reconciliation.approve", "Approve submitted cashier reconciliations"],
  ["device.register", "Register the current POS device"],
  ["device.read", "View POS devices"],
  ["device.manage", "Manage and revoke POS devices"],
  ["sync.read", "View synchronization status"],
  ["sync.execute", "Synchronize offline POS transactions"],
  ["sync.conflict.read", "View offline synchronization conflicts"],
  ["sync.conflict.resolve", "Resolve offline synchronization conflicts"],
];

const all = permissions
  .map(([code]) => code)
  .filter((code) => !code.startsWith("platform."));
const readOnly = [
  "organization.read",
  "branch.read",
  "user.read",
  "role.read",
  "settings.read",
  "catalogue.read",
  "inventory.read",
];
const catalogueManagement = [
  "category.create",
  "category.update",
  "brand.create",
  "brand.update",
  "unit.create",
  "unit.update",
  "product.create",
  "product.update",
  "catalogue.import",
  "catalogue.export",
];
const inventoryManagement = [
  "inventory.opening",
  "inventory.adjust",
  "inventory.transfer",
  "inventory.transfer.receive",
];
const saleOperations = [
  "sale.read",
  "sale.create",
  "sale.hold",
  "sale.cancel_draft",
  "sale.refund",
  "payment.record",
  "receipt.print",
];
const posFoundation = ["organization.read", "branch.read", "catalogue.read"];
const cashierOperations = [
  ...posFoundation,
  ...saleOperations,
  "customer.read",
  "customer.create",
  "device.register",
  "sync.read",
  "sync.execute",
  "reconciliation.submit",
  "shift.open",
  "shift.read",
  "shift.close",
  "shift.cash_movement",
  "alert.read",
];
const phase4Management = [
  "supplier.read",
  "supplier.create",
  "supplier.update",
  "purchase.read",
  "purchase.create",
  "purchase.update_draft",
  "purchase.receive",
  "purchase.cancel_draft",
  "supplier_payment.read",
  "supplier_payment.create",
  "expense.read",
  "expense.create",
  "expense_category.read",
  "expense_category.create",
  "expense_category.update",
  "customer.read",
  "customer.create",
  "customer.update",
  "customer_balance.read",
  "customer_payment.read",
  "customer_payment.create",
  "sale.credit",
];
const appointmentOperations = [
  "staff.read",
  "staff_availability.read",
  "appointment.read",
  "appointment.read_all",
  "appointment.create",
  "appointment.update",
  "appointment.confirm",
  "appointment.start",
  "appointment.complete",
  "appointment.cancel",
  "appointment.no_show",
  "appointment.checkout",
];
const phase5Management = [
  ...appointmentOperations,
  "staff.create",
  "staff.update",
  "staff_availability.manage",
  "commission_rule.read",
  "commission_rule.create",
  "commission_rule.update",
  "commission.read",
  "commission.read_all",
];
const operationalReports = [
  "report.dashboard",
  "report.sales",
  "report.sales.cost",
  "report.profit",
  "report.payments",
  "report.inventory",
  "report.inventory.valuation",
  "report.purchases",
  "report.suppliers",
  "report.expenses",
  "report.customers",
  "report.customer_balances",
  "report.appointments",
  "report.commissions",
  "report.export",
  "reconciliation.read_all",
  "reconciliation.approve",
  "shift.approve",
  "alert.manage",
];
const syncManagement = [
  "device.register",
  "device.read",
  "device.manage",
  "sync.read",
  "sync.execute",
  "sync.conflict.read",
  "sync.conflict.resolve",
];
const rolePermissions = {
  OWNER: all,
  ADMIN: all.filter((code) => code !== "billing.manage"),
  MANAGER: [
    ...readOnly,
    "branch.create",
    "branch.update",
    "user.invite",
    "user.update",
    "user.remove",
    "role.assign",
    "audit.read",
    "settings.update",
    ...catalogueManagement,
    ...inventoryManagement,
    ...saleOperations,
    "sale.discount",
    "product.cost.read",
    ...phase4Management,
    ...phase5Management,
    ...operationalReports,
    ...syncManagement,
  ],
  BRANCH_MANAGER: [
    ...readOnly,
    "branch.update",
    "user.invite",
    "user.update",
    "user.remove",
    "role.assign",
    "audit.read",
    ...catalogueManagement,
    ...inventoryManagement,
    ...saleOperations,
    "sale.discount",
    "product.cost.read",
    ...phase4Management,
    ...phase5Management,
    ...operationalReports,
    ...syncManagement,
  ],
  ACCOUNTANT: [
    ...readOnly,
    "audit.read",
    "sale.read",
    "receipt.print",
    "product.cost.read",
    "supplier.read",
    "purchase.read",
    "supplier_payment.read",
    "supplier_payment.create",
    "expense.read",
    "expense.create",
    "expense_category.read",
    "customer.read",
    "customer_balance.read",
    "customer_payment.read",
    "customer_payment.create",
    "commission_rule.read",
    "commission.read",
    "commission.read_all",
    "report.dashboard",
    "report.sales",
    "report.sales.cost",
    "report.profit",
    "report.payments",
    "report.purchases",
    "report.suppliers",
    "report.expenses",
    "report.customers",
    "report.customer_balances",
    "report.commissions",
    "report.export",
  ],
  INVENTORY_MANAGER: [
    ...readOnly,
    "product.create",
    "product.update",
    ...inventoryManagement,
    "sale.read",
    "product.cost.read",
    "supplier.read",
    "supplier.create",
    "purchase.read",
    "purchase.create",
    "purchase.receive",
    "report.dashboard",
    "report.inventory",
    "report.inventory.valuation",
    "report.purchases",
    "report.suppliers",
    "report.export",
  ],
  POS_SUPERVISOR: [
    ...cashierOperations,
    "sale.discount",
    "sale.credit",
    "customer.update",
    "customer_balance.read",
    "customer_payment.read",
    "customer_payment.create",
    "device.read",
    "sync.conflict.read",
    "sync.conflict.resolve",
    "report.dashboard",
    "report.sales",
    "report.payments",
    "reconciliation.read_all",
    "reconciliation.approve",
    "staff.read",
    "staff_availability.read",
    "appointment.read",
    "appointment.read_all",
    "appointment.create",
    "appointment.checkout",
  ],
  CASHIER: cashierOperations,
  SERVICE_STAFF: [
    ...readOnly,
    "staff.read",
    "staff_availability.read",
    "appointment.read",
    "appointment.start",
    "appointment.complete",
    "commission.read",
    "commission.read_own",
    "report.dashboard",
    "report.appointments",
    "report.commissions",
  ],
  AUDITOR: [
    ...readOnly,
    "audit.read",
    "sale.read",
    "receipt.print",
    "product.cost.read",
    "supplier.read",
    "purchase.read",
    "supplier_payment.read",
    "expense.read",
    "expense_category.read",
    "customer.read",
    "customer_balance.read",
    "customer_payment.read",
    ...operationalReports,
    "device.read",
    "sync.read",
    "sync.conflict.read",
  ],
};

const roleNames = {
  OWNER: "Owner",
  ADMIN: "Administrator",
  MANAGER: "Business Manager",
  BRANCH_MANAGER: "Branch Manager",
  POS_SUPERVISOR: "POS Supervisor",
  CASHIER: "Cashier",
  INVENTORY_MANAGER: "Inventory Manager",
  ACCOUNTANT: "Accountant",
  SERVICE_STAFF: "Service Staff",
  AUDITOR: "Auditor",
};

async function seed() {
  for (const definition of planDefinitions) {
    const plan = await prisma.plan.upsert({
      where: { code: definition.code },
      update: {
        name: definition.name,
        monthlyPriceMinor: definition.monthly,
        annualPriceMinor: definition.annual,
        currency: "QAR",
        isPublic: definition.public,
        isActive: true,
        sortOrder: definition.order,
      },
      create: {
        code: definition.code,
        name: definition.name,
        monthlyPriceMinor: definition.monthly,
        annualPriceMinor: definition.annual,
        currency: "QAR",
        isPublic: definition.public,
        isActive: true,
        sortOrder: definition.order,
      },
    });
    await prisma.planFeature.deleteMany({ where: { planId: plan.id } });
    await prisma.planFeature.createMany({
      data: definition.features.map((featureCode) => ({
        planId: plan.id,
        featureCode,
        enabled: true,
      })),
    });
    await prisma.planLimit.deleteMany({ where: { planId: plan.id } });
    await prisma.planLimit.createMany({
      data: ["branches.max", "users.max", "devices.max", "products.max"].map(
        (limitCode, index) => ({
          planId: plan.id,
          limitCode,
          value: definition.limits[index],
        }),
      ),
    });
  }
  const permissionIds = new Map();
  for (const [code, description] of permissions) {
    const permission = await prisma.permission.upsert({
      where: { code },
      update: { description },
      create: { code, description },
    });
    permissionIds.set(code, permission.id);
  }

  for (const [code, codes] of Object.entries(rolePermissions)) {
    const existing = await prisma.role.findFirst({
      where: { organizationId: null, code },
    });
    const role = existing
      ? await prisma.role.update({
          where: { id: existing.id },
          data: {
            name: roleNames[code] ?? code.replaceAll("_", " "),
            isSystemRole: true,
          },
        })
      : await prisma.role.create({
          data: {
            code,
            name: roleNames[code] ?? code.replaceAll("_", " "),
            isSystemRole: true,
          },
        });

    await prisma.rolePermission.deleteMany({ where: { roleId: role.id } });
    await prisma.rolePermission.createMany({
      data: codes.map((permissionCode) => ({
        roleId: role.id,
        permissionId: permissionIds.get(permissionCode),
      })),
      skipDuplicates: true,
    });
  }
}

seed()
  .then(() => prisma.$disconnect())
  .catch(async (error) => {
    console.error("Database seed failed", error);
    await prisma.$disconnect();
    process.exitCode = 1;
  });
